package io.github.miklires.mauth.audit;

public enum AuditEvent {
    REGISTER,
    LOGIN_SUCCESS,
    LOGIN_FAIL_WRONG_PASSWORD,
    LOGIN_FAIL_LOCKED_OUT,
    LOGIN_FAIL_DISCORD_REQUIRED,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_DISCORD,
    PASSWORD_RESET_CONSOLE,
    DISCORD_LINKED,
    DISCORD_UNLINKED,
    WHITELIST_ADDED,
    WHITELIST_REMOVED,
    LICENSE_ENABLED,
    CAPTCHA_FAILED_OUT_OF_ATTEMPTS,
    FLOOD_TRIGGERED
}
